name: Update docker template

on:
  push:
    branches:
      - main
    paths:
      - "docker/main.tf"
      - ".github/workflows/docker.yaml"
    workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get latest short commit SHA
        id: commit_sha
        run: echo "sha_short=$(git log -1 --pretty=%h)" >> $GITHUB_OUTPUT

      - name: Get commit title
        id: commit_title
        run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
        
      - name: Update Coder template
        uses: matifali/update-coder-template@v3
        with:
          id: docker
          dir: docker
          url: ${{ vars.CODER_URL }}
          name: ${{ steps.commit_sha.outputs.sha_short }}
          message: ${{ steps.commit_title.outputs.title }}
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}
